# Generated by Django 2.2.3 on 2019-07-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroneTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='bronetime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkplace.BroneTime'),
        ),
    ]
