# Generated by Django 2.2.3 on 2019-07-17 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0002_auto_20190715_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='bronetime',
        ),
        migrations.AlterField(
            model_name='bronetime',
            name='time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.CharField(default='free', max_length=10),
        ),
        migrations.CreateModel(
            name='PlaceBrone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bronetime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkplace.BroneTime')),
                ('placenumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkplace.Place')),
            ],
        ),
    ]
