# Generated by Django 2.2.3 on 2019-07-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0003_auto_20190717_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='number',
            field=models.CharField(max_length=4),
        ),
    ]
