# Generated by Django 2.2.3 on 2019-07-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0004_auto_20190718_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='number',
            field=models.IntegerField(),
        ),
    ]
