# Generated by Django 2.2.3 on 2019-07-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0005_auto_20190718_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
