# Generated by Django 2.2.3 on 2019-07-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0006_auto_20190718_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='device_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
