# Generated by Django 2.2.3 on 2019-07-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0007_place_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='bronetime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parkplace.BroneTime'),
        ),
        migrations.DeleteModel(
            name='PlaceBrone',
        ),
    ]
