# Generated by Django 2.2.3 on 2019-07-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkplace', '0008_auto_20190722_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='bronetime',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='BroneTime',
        ),
    ]
